import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";

import { supabase } from "@/src/config/supabase";
import styles from "@/styles/Home.module.css";

import { Auth, Typography, Button } from "@supabase/ui";
import { useEffect, useState } from "react";
import LoginPage from "@/src/components/LoginPage";

//TODO:
// - login page
// - main dashboard
// - cart
// - dynamic routes nextjs
// - users connected db
// - filter component bug

export default function Home() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Carspark E-commerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <LoginPage />
      </main>
    </>
  );
}
